name: CI

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # This checks out your repository's code

    - name: Set up Python 3.8
      uses: actions/setup-python@v4  # Set up Python 3.8
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
